PR for issue #38
strongloop/loopback-example-facade pull request #42
Opened 2017-03-24 16:44 UTC by mpatsute

1. Generated datasource mongoDS
2. Generated model Cheque to talk to mongo DB
3. Updated docker-compose to dockerify mongo

2017-03-24 17:14 UTC, superkhau commented
Please use a more descriptive commit message -- see http://loopback.io/doc/en/contrib/git-commit-messages.html.

2017-03-24 17:17 UTC, superkhau requested changes
One nitpick, LGTM.

2017-03-24 17:17 UTC, superkhau commented on services/transaction/server/datasources.json
> +  "mongoDs": {
Maybe name it something more obvious? mongoService?

2017-03-24 17:17 UTC, superkhau commented on services/transaction/server/model-config.json
> +    "dataSource": "mongoDs",
mongoService

2017-03-24 19:20 UTC, mpatsute commented on services/transaction/server/datasources.json
> +  "mongoDs": {
Renamed mongoDs to mongoService!

2017-03-24 23:14 UTC, superkhau approved these changes

2017-04-03 23:54 UTC, superkhau commented
@mpatsute You should squash the commits into one and use a more descriptive commit message like:

"Use MongoDB in the Transaction microservice".

2017-04-13 17:16 UTC, ritch commented
LGTM

2017-04-13 23:37 UTC, merged